### ISSUE TITLE
Installing 

### ISSUE THREAD

**Issue by Ovens-Syntax** [BentonEdmondson/servitor#1]
Honestly feeling kind of embarrassed to ask this but I have never installed packages manually with from a GitHub release and don't really know how I looked around for awhile but could not figure it out that being said were do I install the .linux.x86_64 file to? sorry to waste your time

**Comment by BentonEdmondson** [comment]
No worries. It looks like right now the standard for most distributions is to put custom binaries in `~/.local/bin`. So do this
* `mkdir -p ~/.local/bin`
* `mv servitor.linux.x86_64 ~/.local/bin/servitor`
* `chmod +x ~/.local/bin/servitor`

Then depending on your distribution you may have to add `~/.local/bin` to `$PATH`. So if `echo $PATH` doesn't contain `~/.local/bin`, then do
* `echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.profile`
* `source ~/.profile`

Let me know if that works.

**Comment by Ovens-Syntax** [comment]
This worked thanks for the help and happy late new year
