### ISSUE TITLE
Mass moderation

### ISSUE THREAD

**Issue by CarolDas** [BentonEdmondson/servitor#3]
How do I integrate the [FediBlackBook API](https://fediblackbook.com/) with Servitor for bulk blocking?

**Comment by BentonEdmondson** [comment]
Right now there's no way to. I think it would be pretty easy to implement. The config file would just accept a list of URLs which represent lists of people to block. There could also be a way to explicitly whitelist accounts/instances you like that are controversial. (Also accounts you subscribe to would probably be auto-whitelisted.)

The block list you link is here: https://fbb.onl/api/data
It looks like Mastodon also has an endpoint with all instances blocked by an instance: https://mastodon.social/api/v1/instance/domain_blocks
Perhaps there are other block list formats that exist.

I'm not going to be implementing this anytime soon but would be willing to take a patch.

**Comment by BentonEdmondson** [comment]
Another thing I thought of is there could be a configurable way to censor individual words or phrases.
